# 请不要修改此文件的参数
parameters:
    disabled_features: []
    cloud_client:
        arguments: 
            videoCommands:
                avthumb/m3u8/segtime/10/preset/video_240k : sd
                avthumb/m3u8/segtime/10/preset/video_440k : hd
                avthumb/m3u8/segtime/10/preset/video_640k : shd
                # avthumb/mp4/r/24/vb/256k/vcodec/libx264/ar/22050/ab/64k/acodec/libfaac : sd
                # avthumb/mp4/r/24/vb/512k/vcodec/libx264/ar/44100/ab/64k/acodec/libfaac : hd
                # avthumb/mp4/r/24/vb/1024k/vcodec/libx264/ar/44100/ab/64k/acodec/libfaac : shd
            audioCommands: []
    cdn_path: http://cdn.staticfile.org
